# Generated by Django 6.0 on 2025-12-23 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('GENERIC', 'Generic'), ('ENTEPRISE', 'Enterprise'), ('BUSINESS_UNIT', 'Business Unit'), ('SITE', 'Site'), ('LINE', 'Line'), ('CELL', 'Cell'), ('MACHINE', 'Machine')], default='GENERIC', max_length=30),
        ),
        migrations.AddField(
            model_name='asset',
            name='can_record_downtime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='can_run_production',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.asset'),
        ),
    ]
